name: Build & upload to Firebase App Distribution

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # load keystore properties to ci pipe-line
      - name: Decrypt And Load DOG App KeyStore Properties File
        env:
          KEYSTORE_PROPERTIES: ${{secrets.KEYSTORE_PROPERTIES}}
          run: dev_config/keystore.properties

      # load keystore file to ci pipe-line
      - name: Decrypt And Load DOG App KeyStore File
        env:
          ENCRYPT_SECRET_KEY: ${{secrets.ENCRYPT_SECRET_KEY}}
          run: dev_config/docapp.jks

      # clean before building signed apk
      - name: SastaSundar Build Clean Up
        run: ./gradlew clean --stacktrace

      - name: build debug
        run: ./gradlew clean assembleDebug --stacktrace

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: QA
          file: app/debug/app-debug12.apk