name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

      # clean before building signed apk
    - name: DogApp Build Clean Up
      run: ./gradlew clean --stacktrace

      # assemble signed apk
    - name: Assemble DogApp Debug Build
      run: ./gradlew clean assembleDebug --stacktrace

      # upload signed apk to firebase app distribution
    - name: build debug
      run: ./gradlew assembleDebug

    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: Debug
        file: app/build/outputs/apk/debug/app-debug.apk

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
