name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
      - name: checkout
        uses: actions/checkout@v3

    # Set Up JDK
    - name: Setup Java JDK
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
