
name: Android Pull Request & Master CI & CD to Firebase

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Upload apk to App Tester
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '11'
          distribution: 'adopt'

      # load apiKeys to ci pipe-line
      - name: Decrypt DOG API Keys
        env:
          SS_APP_API_KEYS: ${{secrets.DOG_APP_API_KEYS}}
        run: |
          openssl aes-256-cbc -d -in dev_config/apiKey.properties.encrypted -k $DOG_APP_API_KEYS >> dev_config/apiKey.properties


      # load keystore properties to ci pipe-line
      - name: Decrypt And Load Dog App KeyStore Properties File
        env:
          KEYSTORE_PROPERTIES: ${{secrets.KEYSTORE_PROPERTIES}}
        run: |
          openssl aes-256-cbc -d -in dev_config/keystore.properties.encrypted -k $KEYSTORE_PROPERTIES >> dev_config/keystore.properties

      # load keystore file to ci pipe-line
      - name: Decrypt And Load Dog App KeyStore File
        env:
          ENCRYPT_SECRET_KEY: ${{secrets.ENCRYPT_SECRET_KEY}}
        run: |
          openssl aes-256-cbc -d -in dev_config/dogapp.jks.encrypted -k $ENCRYPT_SECRET_KEY >> dev_config/dogapp.jks

      # clean before building signed apk
      - name: Dog Build Clean Up
        run: ./gradlew clean --stacktrace

      - name: build release
        run: bash ./gradlew assembleDebug
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: qa
          file: app/build/outputs/apk/debug/app-debug12.apk
          debug: true

            # Build deployment to diawi site
      - name: Upload Debug Build to Diawi
        uses: rnkdsh/action-upload-diawi@v1.2.1
        with:
          token: '8wh6c1ZNMbb7SsBanetw1CTeJBSt4SOaO4BjMPugNs'
          file: app/build/outputs/apk/debug/app-debug12.apk
          password: soumen321
          recipients: bhattacharjee.soumen@gmail.com

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.3
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug12.apk

