
name: Android Pull Request & Master CI & CD to Firebase

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Upload apk to App Tester
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: build release
        run: bash ./gradlew assembleDebug
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: '1:1025175451093:android:217f1c24cc8af6cc74395c'
          token: '1//0grhZZ4hf_MJfCgYIARAAGBASNwF-L9Irh4MuDCrHihAR1cFrMTbbMyiKL3J8B3PRB9X0OAD0Pn7As8NMUsIdelv6G9VzjY-MJDM'
          groups: QA
          file: ./app/build/intermediates/apk/debug/app-debug12.apk

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.3
        with:
          name: app
          path: ./app/build/intermediates/apk/debug/app-debug12.apk